version: '3.5'

services:
  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  react-frontend:
    build:
      context: /home/mauro/craftech-docker/devops-challenge/frontend
      dockerfile: Dockerfile
    #image: craftech/react1.0:latest
    #container_name: craftech/react 
    restart: unless-stopped      
    ports:
      - "3000:3000"
    #volumes:
    #  - ./frontend:/app


  django-backend:
    build:
      context: /home/mauro/craftech-docker/devops-challenge/backend
      dockerfile: Dockerfile
    #image: craftech/image-django1.0:latest
    #container_name: craftech/django
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    #command: python manage.py runserver 0.0.0.0:8000
    environment:
    - SECREY_KEY=12345
    

