version: '3.5'

services:
  react-frontend:
    #build:
    #  context: ~/craftech-docker/devops-challenge/frontend
    #  dockerfile: Dockerfile
    image: gat77/craftech-react:1.0
    #container_name: craftech/react 
    restart: unless-stopped      
    ports:
      - "3000:3000"
    #volumes:
    #  - ./frontend:/app

  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  django-backend:
    #build:
    #  context: ~/craftech-docker/devops-challenge/backend
    #  dockerfile: Dockerfile
    image: gat77/craftech-django:1.0
    #container_name: craftech/django
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres  
    #command: python manage.py runserver 0.0.0.0:8000
    environment:
    - SECREY_KEY=12345
    
